language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
before_install:
  - cd rest-countries-api-with-color-theme-switcher-react-ts/
install:
  - yarn install
script:
  - yarn run build
